comment: false

coverage:
  status:
    patch: no
    changes: no
    project:
      default:
        target: 100%
        threshold: null


codecov:
  require_ci_to_pass: yes
  notify:
    wait_for_ci: yes
    after_n_builds: 2
